name: culvert-vision
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip
  # Cookiecutter packages
  - click
  - Sphinx
  - coverage
  - awscli=1.27.*
  - flake8
  - python-dotenv>=0.5.1
  # Additional packages
  - black
  - isort
  - rclone
  - geopandas
  - notebook