name: culvert-vision
channels:
  - conda-forge
dependencies:
  - python=3.11
  # Cookiecutter packages
  - click
  - Sphinx
  - coverage
  - awscli=1.27.*
  - flake8
  - python-dotenv>=0.5.1
  # Additional packages
  - isort
  - rclone
  - geopandas
  - pyarrow
  - notebook
  - pydantic
  - python-pdal
  - pip
  - pip:
      - black[jupyter]
      - -e .