name: culvert-vision
channels:
  - conda-forge
dependencies:
  - python=3.11
  # Cookiecutter packages
  - click
  - Sphinx
  - coverage
  - awscli=1.27.*
  - flake8
  - python-dotenv>=0.5.1
  # Additional packages
  - isort
  - black
  - black-jupyter
  - pytest
  - rclone
  - geopandas
  - pandera
  - pyarrow
  - notebook
  - python-pdal
  - pystac-client
  - rasterio
  - loguru
  - gdal
  - psycopg
  - python-duckdb
  - pip
  - pip:
      - dbt-duckdb
      - dbt-postgres
      - -e .