vector_transform:
  outputs:

    dev:
      type: postgres
      threads: 4
      host: "{{ env_var('POSTGRES_HOST') }}"
      port: "{{ env_var('POSTGRES_PORT') | int }}"
      user: "{{ env_var('POSTGRES_USER') }}"
      pass: "{{ env_var('POSTGRES_PASS') }}"
      dbname: "{{ env_var('POSTGRES_DB') }}"
      schema: "public"

  target: dev
